name: Docker File On Push 
on:
  push:
    branches:
      - main
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Login 
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Images 
        run: |
          docker build -f /my_app/Dockerfile -t devendra110203/myapp:latest /my_app
      - name: Push On Docker Hub
        run: |
          docker push devendra110203/myapp:latest
