name: Docker File On Push 
on:
  push:
    branches:
      - main
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Login 
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Images 
        run: |
          docker build -f my_app/Dockerfile -t devendra110203/myapp:latest my_app
      - name: Push On Docker Hub
        run: |
          docker push devendra110203/myapp:latest

      - name: Authentication to google cloud
        uses: google-github-actions/auth@v0
        with:
           credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Publish Messge 
        uses: miraliumre/actions-pubsub@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          topic_name: ${{ TOPIC_NAME }}
          message: '{"name:"devendra"}'
